openapi: 3.0.1
info:
  title: Exchange
  description: REST API endpoints for chat app
  version: 0.0.0-SNAPSHOT
servers:
  - url: 'api/v1'
components:
  schemas:
    RoleDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: identifier the role
        type:
          $ref: '#/components/schemas/USER_IN_GROUP_ROLE'
        description:
          type: string
          description: role description
    USER_IN_GROUP_ROLE:
      type: string
      enum:
        - ADMIN
        - MEMBER
        - SUPER_ADMIN
    PERMISSIONS:
      type: string
      enum:
        - user:create
        - user:read
        - user:edit